package orchestrator

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"github.com/kandev/kandev/internal/task/models"
	protocol "github.com/kandev/kandev/pkg/codexappserver"
)

var (
	ErrCodexForkUnsupported = errors.New("native Codex conversation fork is unavailable")
	ErrCodexForkActive      = errors.New("conversation can only be forked after all work has settled")
	ErrCodexForkUncertain   = errors.New("the provider fork result is uncertain; this request cannot be retried")
	ErrCodexForkInProgress  = errors.New("this conversation fork request is already in progress")
)

const (
	codexForkStatusPending       = "pending"
	codexForkStatusUncertain     = "uncertain"
	codexForkStatusProviderReady = "provider_ready"
	codexForkStatusSessionReady  = "session_ready"
	codexForkStatusComplete      = "complete"
	codexForkProviderTurnKey     = "provider_turn_id"
	codexForkProviderThreadKey   = "provider_thread_id"
	codexForkDestinationKey      = "destination_session_id"
	codexForkStatusKey           = "status"
)

// ForkConversationRequest identifies the source Kandev session/turn and an
// idempotency key generated by the requesting client.
type ForkConversationRequest struct {
	TaskID          string
	SourceSessionID string
	TurnID          string
	RequestID       string
}

type ForkConversationResponse struct {
	TaskID    string `json:"task_id"`
	SessionID string `json:"session_id"`
	State     string `json:"state"`
}

type nativeConversationForker interface {
	ForkSessionBySessionID(ctx context.Context, sessionID, providerTurnID string) (string, error)
}

// ForkConversation forks a completed native Codex turn into a new session on
// the same task, profile, executor, and task environment. A durable request
// marker is written before provider RPC; an ambiguous RPC result is never
// blindly retried.
func (s *Service) ForkConversation(ctx context.Context, req ForkConversationRequest) (*ForkConversationResponse, error) {
	if s == nil || s.repo == nil || s.turnService == nil {
		return nil, errors.New("conversation fork storage is unavailable")
	}
	state, err := s.newCodexForkOperation(ctx, req)
	if err != nil {
		return nil, err
	}
	completed, err := s.resumeCodexForkOperation(ctx, state)
	if err != nil || completed != nil {
		return completed, err
	}
	if err := s.validateCodexForkTurn(ctx, state); err != nil {
		return nil, err
	}
	if err := s.ensureCodexForkProviderThread(ctx, state); err != nil {
		return nil, err
	}
	if err := s.ensureCodexForkDestination(ctx, state); err != nil {
		return nil, err
	}
	if err := s.bindCodexForkDestination(ctx, state); err != nil {
		return nil, err
	}
	state.operation[codexForkStatusKey] = codexForkStatusComplete
	if err := s.repo.SetSessionMetadataKey(ctx, state.source.ID, state.operationKey, state.operation); err != nil {
		return nil, fmt.Errorf("persist completed fork operation: %w", err)
	}
	return s.codexForkResponse(ctx, state.request.TaskID, state.destinationID)
}

type codexForkOperation struct {
	request          ForkConversationRequest
	requestID        uuid.UUID
	source           *models.TaskSession
	operationKey     string
	operation        map[string]interface{}
	hasOperation     bool
	resumeExisting   bool
	forker           nativeConversationForker
	providerTurnID   string
	providerThreadID string
	destinationID    string
}

func (s *Service) newCodexForkOperation(ctx context.Context, req ForkConversationRequest) (*codexForkOperation, error) {
	requestID, err := uuid.Parse(strings.TrimSpace(req.RequestID))
	if err != nil || requestID == uuid.Nil {
		return nil, errors.New("request_id must be a non-empty UUID")
	}
	req.RequestID = requestID.String()
	if req.TaskID == "" || req.SourceSessionID == "" || req.TurnID == "" {
		return nil, errors.New("task_id, source_session_id, and turn_id are required")
	}
	if !s.config.CodexAppServerEnabled {
		return nil, ErrCodexForkUnsupported
	}
	if err := s.authorizeTaskSessionPair(ctx, req.TaskID, req.SourceSessionID); err != nil {
		return nil, err
	}
	if err := s.authorizeSessionPrompt(ctx, req.SourceSessionID); err != nil {
		return nil, err
	}
	source, err := s.repo.GetTaskSession(ctx, req.SourceSessionID)
	if err != nil {
		return nil, err
	}
	if source == nil || source.TaskID != req.TaskID {
		return nil, errors.New("source session does not belong to task")
	}
	if models.StringFromAny(source.AgentProfileSnapshot["agent_id"]) != codexAppServerAgentType {
		return nil, ErrCodexForkUnsupported
	}
	operationKey := models.SessionMetaKeyCodexForkRequestPrefix + requestID.String()
	operationValue, hasOperation := source.Metadata[operationKey]
	return &codexForkOperation{
		request: req, requestID: requestID, source: source, operationKey: operationKey,
		operation: readCodexForkOperation(operationValue), hasOperation: hasOperation,
	}, nil
}

func (s *Service) resumeCodexForkOperation(ctx context.Context, state *codexForkOperation) (*ForkConversationResponse, error) {
	if s.agentManager != nil {
		state.forker, _ = s.agentManager.(nativeConversationForker)
	}
	if state.hasOperation {
		switch state.operation[codexForkStatusKey] {
		case codexForkStatusComplete:
			return s.codexForkResponse(ctx, state.request.TaskID, models.StringFromAny(state.operation[codexForkDestinationKey]))
		case codexForkStatusProviderReady, codexForkStatusSessionReady:
			state.resumeExisting = true
		case codexForkStatusUncertain:
			return nil, ErrCodexForkUncertain
		default:
			return nil, ErrCodexForkInProgress
		}
	} else if state.forker == nil {
		// Do not persist an idempotency marker for an operation this service
		// composition cannot execute. A later request may reach a capable manager.
		return nil, ErrCodexForkUnsupported
	}
	return nil, nil
}

func (s *Service) validateCodexForkTurn(ctx context.Context, state *codexForkOperation) error {
	turn, err := s.turnService.GetTurn(ctx, state.request.TurnID)
	if err != nil {
		return err
	}
	if turn == nil || turn.TaskSessionID != state.source.ID || turn.CompletedAt == nil ||
		models.StringFromAny(turn.Metadata["agent_type"]) != codexAppServerAgentType {
		return ErrCodexForkActive
	}
	state.providerTurnID = models.StringFromAny(turn.Metadata[models.TurnMetaKeyCodexNativeTurnID])
	if state.providerTurnID == "" {
		return errors.New("completed turn has no native Codex identity")
	}
	if state.resumeExisting {
		if models.StringFromAny(state.operation[codexForkProviderTurnKey]) != state.providerTurnID {
			return ErrCodexForkUncertain
		}
		return nil
	}
	return s.beginCodexForkOperation(ctx, state)
}

func (s *Service) beginCodexForkOperation(ctx context.Context, state *codexForkOperation) error {
	if state.source.State != models.TaskSessionStateWaitingForInput {
		return ErrCodexForkActive
	}
	active, err := s.turnService.GetActiveTurn(ctx, state.source.ID)
	if err != nil {
		return err
	}
	if active != nil {
		return ErrCodexForkActive
	}
	state.operation = map[string]interface{}{
		codexForkProviderTurnKey: state.providerTurnID,
		codexForkStatusKey:       codexForkStatusPending,
	}
	created, err := s.repo.SetSessionMetadataKeyIfAbsent(ctx, state.source.ID, state.operationKey, state.operation)
	if err != nil {
		return err
	}
	if !created {
		return ErrCodexForkInProgress
	}
	return nil
}

func (s *Service) ensureCodexForkProviderThread(ctx context.Context, state *codexForkOperation) error {
	state.providerThreadID = models.StringFromAny(state.operation[codexForkProviderThreadKey])
	if state.providerThreadID != "" {
		return nil
	}
	if state.forker == nil {
		return ErrCodexForkUnsupported
	}
	forkCtx, cancel := context.WithTimeout(ctx, 45*time.Second)
	providerThreadID, err := state.forker.ForkSessionBySessionID(forkCtx, state.source.ID, state.providerTurnID)
	cancel()
	if err != nil || strings.TrimSpace(providerThreadID) == "" {
		if errors.Is(err, protocol.ErrForkPrecondition) {
			return s.releaseRefusedCodexForkOperation(ctx, state, err)
		}
		return s.markCodexForkUncertain(ctx, state, err)
	}
	state.providerThreadID = providerThreadID
	state.operation[codexForkProviderThreadKey] = providerThreadID
	state.operation[codexForkStatusKey] = codexForkStatusProviderReady
	if err := s.repo.SetSessionMetadataKey(ctx, state.source.ID, state.operationKey, state.operation); err != nil {
		return s.markCodexForkUncertain(ctx, state, fmt.Errorf("persist provider fork identity: %w", err))
	}
	return nil
}

func (s *Service) releaseRefusedCodexForkOperation(ctx context.Context, state *codexForkOperation, forkErr error) error {
	remover, ok := s.repo.(interface {
		RemoveSessionMetadataKeyIfJSONValue(context.Context, string, string, interface{}) (bool, error)
	})
	if !ok {
		return fmt.Errorf("fork was refused before provider RPC but its request marker cannot be released: %w", ErrCodexForkInProgress)
	}
	released, err := remover.RemoveSessionMetadataKeyIfJSONValue(ctx, state.source.ID, state.operationKey, state.operation)
	if err != nil {
		return fmt.Errorf("fork was refused before provider RPC but its request marker could not be released: %w", err)
	}
	if !released {
		return ErrCodexForkInProgress
	}
	return forkErr
}

func (s *Service) markCodexForkUncertain(ctx context.Context, state *codexForkOperation, forkErr error) error {
	state.operation[codexForkStatusKey] = codexForkStatusUncertain
	_ = s.repo.SetSessionMetadataKey(ctx, state.source.ID, state.operationKey, state.operation)
	if forkErr == nil {
		forkErr = errors.New("provider fork returned no thread identity")
	}
	return fmt.Errorf("%w: %w", ErrCodexForkUncertain, forkErr)
}

func (s *Service) ensureCodexForkDestination(ctx context.Context, state *codexForkOperation) error {
	state.destinationID = models.StringFromAny(state.operation[codexForkDestinationKey])
	if state.destinationID != "" {
		return nil
	}
	destinationID, err := s.PrepareTaskSession(ctx, state.request.TaskID, state.source.AgentProfileID, state.source.ExecutorID, state.source.ExecutorProfileID, "", false)
	if err != nil {
		return err
	}
	state.destinationID = destinationID
	state.operation[codexForkDestinationKey] = destinationID
	state.operation[codexForkStatusKey] = codexForkStatusSessionReady
	if err := s.repo.SetSessionMetadataKey(ctx, state.source.ID, state.operationKey, state.operation); err != nil {
		s.removeUnboundCodexForkSession(ctx, state, destinationID)
		return fmt.Errorf("persist fork destination identity: %w", err)
	}
	return nil
}

func (s *Service) bindCodexForkDestination(ctx context.Context, state *codexForkOperation) error {
	destination, err := s.repo.GetTaskSession(ctx, state.destinationID)
	if err != nil {
		return err
	}
	if destination == nil || destination.TaskID != state.request.TaskID {
		return errors.New("persisted fork destination is unavailable")
	}
	destination.DownstreamACPSessionID = state.providerThreadID
	if err := s.repo.UpdateTaskSession(ctx, destination); err != nil {
		s.removeUnboundCodexForkSession(ctx, state, destination.ID)
		s.resetCodexForkDestination(ctx, state)
		return fmt.Errorf("persist fork destination session: %w", err)
	}
	return s.persistCodexForkLineage(ctx, state, destination.ID)
}

func (s *Service) persistCodexForkLineage(ctx context.Context, state *codexForkOperation, destinationID string) error {
	lineage := []struct{ key, value string }{
		{"codex_fork_source_session_id", state.source.ID},
		{"codex_fork_source_turn_id", state.request.TurnID},
		{"codex_fork_request_id", state.requestID.String()},
		{"codex_fork_provider_thread_id", state.providerThreadID},
	}
	for _, item := range lineage {
		if err := s.repo.SetSessionMetadataKey(ctx, destinationID, item.key, item.value); err != nil {
			s.removeUnboundCodexForkSession(ctx, state, destinationID)
			s.resetCodexForkDestination(ctx, state)
			return fmt.Errorf("persist fork lineage metadata: %w", err)
		}
	}
	return nil
}

func (s *Service) removeUnboundCodexForkSession(ctx context.Context, state *codexForkOperation, sessionID string) {
	if cleanupErr := s.deleteSessionAndPublishRemoval(ctx, state.request.TaskID, sessionID); cleanupErr != nil {
		s.logger.Warn("failed to remove unbound Codex fork session", zap.String("session_id", sessionID), zap.Error(cleanupErr))
	}
}

func (s *Service) resetCodexForkDestination(ctx context.Context, state *codexForkOperation) {
	state.operation[codexForkStatusKey] = codexForkStatusProviderReady
	state.operation[codexForkDestinationKey] = ""
	_ = s.repo.SetSessionMetadataKey(ctx, state.source.ID, state.operationKey, state.operation)
}

func readCodexForkOperation(value interface{}) map[string]interface{} {
	encoded, err := json.Marshal(value)
	if err != nil {
		return map[string]interface{}{}
	}
	operation := map[string]interface{}{}
	if err := json.Unmarshal(encoded, &operation); err != nil {
		return map[string]interface{}{}
	}
	return operation
}

func (s *Service) codexForkResponse(ctx context.Context, taskID, sessionID string) (*ForkConversationResponse, error) {
	if sessionID == "" {
		return nil, errors.New("completed fork operation has no destination session")
	}
	session, err := s.repo.GetTaskSession(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	if session == nil || session.TaskID != taskID {
		return nil, errors.New("fork destination session is unavailable")
	}
	return &ForkConversationResponse{TaskID: taskID, SessionID: session.ID, State: string(session.State)}, nil
}
